[versions]
junit = "6.0.1"
gson = "2.13.2"
jansi = "2.4.2"

[libraries]
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
jansi = { group = "org.fusesource.jansi", name = "jansi", version.ref = "jansi" }
